### ISSUE TITLE
How would I disable the superman-rom power menu?

### ISSUE THREAD

**Issue by seiterseiter** [Tkkg1994/SuperMan-Rom#1]
As the title says, im just looking for a way to disable the power menu that superman-rom adds when you hold down the power button.

Thanks :)

**Comment by Tkkg1994** [comment]
Hello :)

You can disable all mods in that menu when you choose stock services.jar in aroma installer, that's what it's for :+1:

**Comment by seiterseiter** [comment]
What else is in services.jar though?

**Comment by Tkkg1994** [comment]
back to kill for example, volume warning disabled and some other small things from romcontrol (also torchlight in reboot menu, screencast)
